### PR TITLE
dockerized

### PR DESCRIPTION
**Pull request by davidhfrankelcodes**
Hello there! Your app is cool! I made a Dockerfile and corresponding docker-compose.yaml file for this!

Just run 

```
# build the image with...
docker compose build
# Start the container with...
docker compose up 
# or run in detached mode like...
docker compose up -d
# bring it back down with
docker compose down
```

### CODE REVIEW

**Comment by OmitNomis** [comment]
Hey, could you please explain to me when you'd use this? 
I've never actually used docker aside from when i need to host stuff on a VPS, and this his hosted on vercel.

And, maybe you could also add the instructions to run/build/stop the container in the readme file

**Comment by davidhfrankelcodes** [comment]
> Hey, could you please explain to me when you'd use this? I've never actually used docker aside from when i need to host stuff on a VPS, and this his hosted on vercel.
> 
> And, maybe you could also add the instructions to run/build/stop the container in the readme file

I Added the docker instructions to the README.

You can use this to run the app if for example you don't have node installed on your machine. This also starts a daemon that restarts when you reboot the machine, so it's also a deployment (don't need systemd or whatever to run it).

**Comment by OmitNomis** [comment]
Oh cool, I didn't know using it restarts even when rebooting the system. Thanks.

**Review by OmitNomis — APPROVED** [review]

**Comment by davidhfrankelcodes** [comment]
> Oh cool, I didn't know using it restarts even when rebooting the system. Thanks.

lol it would do this if I actually put in the restart instructions!

I just made another commit with restart instructions. Now, when the container is created the first time it will restart on reboot.

**Comment by OmitNomis** [comment]
Ohh, okay that makes sense. 
Thanks, it's great learning new stuff :>

**Comment by BartoszJarocki** [comment]
I guess this would trigger people on twitter but hey, let's make it possible to deploy it outside of vercel. here's an official example of dockerfile - https://github.com/vercel/next.js/blob/canary/examples/with-docker/Dockerfile. would you mind checking what can be improved in this PR to make it possible to deploy outside of vercel?

**Comment by davidhfrankelcodes** [comment]
> ould you mind checking what can be improved in this PR to make it possible to deploy outside of vercel?

Already possible to run outside of vercel as is. That's the point of the PR as is. Don't need to do anything else.

**Pull request merged**
